// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isUnlocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_unlocked");
},
/**
 * Async so the (possibly seconds-long) Touch ID sheet never blocks the main
 * thread. First run generates the key silently; later runs prompt.
 */
async unlock() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lock() : Promise<void> {
    await TAURI_INVOKE("lock");
},
/**
 * Recovery path when the stored data can no longer be decrypted (the
 * keychain item was deleted/regenerated). Quarantines the old database
 * (rename, never delete) and unlocks against a fresh one. The UI gates this
 * behind an explicit typed confirmation.
 */
async startFresh() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_fresh") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDocuments() : Promise<Result<DocMeta[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_documents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDocument(id: string) : Promise<Result<Document, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDocument(id: string | null, title: string | null, body: string) : Promise<Result<DocMeta, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_document", { id, title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePin(id: string) : Promise<Result<DocMeta, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pin", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDocument(id: string) : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_document", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Async so a full-archive body scan cannot freeze the UI thread.
 */
async search(query: string, scopeArchived: boolean) : Promise<Result<SearchHit[], CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search", { query, scopeArchived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storageStats() : Promise<Result<StorageStats, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("storage_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runRetentionNow() : Promise<Result<RetentionReport, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_retention_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Settings are readable before unlock (the unlock screen is themed).
 */
async getSettings() : Promise<Result<Settings, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSettings(settings: Settings) : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Checklist progress derived from the body at save time, so list rendering
 * never needs to decrypt bodies.
 */
export type ChecklistCounts = { done: number; total: number }
/**
 * Single error surface crossing IPC, serialized as a tagged union so the
 * frontend can react to specific kinds (e.g. `locked` → show unlock screen).
 */
export type CoreError = { kind: "locked" } | { kind: "keychainDenied" } | { kind: "keychainItemMissing" } | { kind: "storageFull" } | { kind: "notFound" } | { kind: "io"; detail: string } | { kind: "corrupt"; detail: { id: string } }
/**
 * Listing/browse metadata — everything the UI needs without the body.
 * Stored encrypted as its own blob, decrypted into the in-memory catalog
 * on unlock.
 */
export type DocMeta = { id: string; title: string | null; 
/**
 * First non-empty line of the body, truncated; display name fallback.
 */
preview: string; createdAt: number; 
/**
 * Last content edit (edits and checkbox toggles only — opening a
 * document does NOT refresh this). Drives the whole retention policy.
 */
updatedAt: number; pinned: boolean; archivedAt: number | null; 
/**
 * Size of the plaintext body in bytes.
 */
sizeBytes: number; checklist: ChecklistCounts | null }
/**
 * A full document as the editor sees it.
 */
export type Document = { 
/**
 * UUIDv7 (time-ordered).
 */
id: string; title: string | null; body: string; meta: DocMeta }
export type RetentionReport = { archived: number; deletedByAge: number; deletedBySpace: number; 
/**
 * Destructive passes were skipped because system time regressed.
 */
skippedClockSkew: boolean }
export type SearchHit = { meta: DocMeta; 
/**
 * Snippet around the first match (from title/preview or body).
 */
snippet: string; 
/**
 * True when the match came from the body rather than title/preview.
 */
inBody: boolean }
export type Settings = { theme: string; 
/**
 * Font id from the frontend registry (serde defaults keep settings.json
 * files written before these fields existed loading cleanly).
 */
font?: string; 
/**
 * Root font size in px — the rem base the whole UI scales from.
 */
fontSize?: number; 
/**
 * Enabled dashboard panels, in display order ("activity", "tasks",
 * "storage"); empty hides the dashboard.
 */
dashboardPanels?: string[]; 
/**
 * Dashboard glyph style id ("blocks", "braille", "shade").
 */
dashboardStyle?: string; 
/**
 * Dashboard size id ("small", "medium", "large").
 */
dashboardSize?: string }
export type StorageStats = { dbBytes: number; limitBytes: number; docCount: number; archivedCount: number; pinnedCount: number; 
/**
 * True when over the limit but only pinned documents remain — saves are
 * refused until the user unpins or deletes something.
 */
overCapacity: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
