// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isUnlocked() : Promise<boolean> {
    return await TAURI_INVOKE("is_unlocked");
},
/**
 * Async so the (possibly seconds-long) Touch ID sheet never blocks the main
 * thread. First run generates the key silently; later runs prompt.
 */
async unlock() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async lock() : Promise<void> {
    await TAURI_INVOKE("lock");
},
/**
 * Recovery path when the stored data can no longer be decrypted (the
 * keychain item was deleted/regenerated). Quarantines the old database
 * (rename, never delete) and unlocks against a fresh one. The UI gates this
 * behind an explicit typed confirmation.
 */
async startFresh() : Promise<Result<null, CoreError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_fresh") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Single error surface crossing IPC, serialized as a tagged union so the
 * frontend can react to specific kinds (e.g. `locked` → show unlock screen).
 */
export type CoreError = { kind: "locked" } | { kind: "keychainDenied" } | { kind: "keychainItemMissing" } | { kind: "storageFull" } | { kind: "notFound" } | { kind: "io"; detail: string } | { kind: "corrupt"; detail: { id: string } }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
